### ISSUE TITLE
Misleading installation instructions

### ISSUE THREAD

**Issue by mudrd8mz** [julenpardo/moodle-local_resourceexporter#21]
The installation instructions at the https://moodle.org/plugins/local_resourceexporter read

    Clone this repository to a directory named usablebackup

I believe the "usablebackup" is a mistake, probably forgotten relic of a previous version of the tool.

**Comment by julenpardo** [comment]
Hi David,

Thanks for opening these issues.

Yep, that was the previous name of the tool. I've updated it in the README of the repo, and in the directory's page, I've just indicated the steps to download and unzip the the file downloaded from the directory itself, since it does not have many sense to speak about the repo cloning.
